// <auto-generated />
using System;
using FritApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FritApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816124339_AddVotaciones")]
    partial class AddVotaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FritApi.Models.AuditAuthorizedUser", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId");

                    b.ToTable("AuditAuthorizedUsers");
                });

            modelBuilder.Entity("FritApi.Models.AuditEntry", b =>
                {
                    b.Property<long>("AuditEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditEntryId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("text");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("text");

                    b.HasKey("AuditEntryId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "Entidad");

                    b.HasIndex("TenantId", "UsuarioId");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("FritApi.Models.CinePelicula", b =>
                {
                    b.Property<int>("CinePeliculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CinePeliculaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("GrupoPelicula")
                        .HasColumnType("integer")
                        .HasColumnName("Grupo_pelicula");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("integer");

                    b.HasKey("CinePeliculaId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioCreadorId");

                    b.ToTable("CinePeliculas");
                });

            modelBuilder.Entity("FritApi.Models.CineValoracion", b =>
                {
                    b.Property<int>("CineValoracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CineValoracionId"));

                    b.Property<int>("CinePeliculaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("NombreMostrado")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Nota")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("CineValoracionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("CinePeliculaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("CineValoraciones");
                });

            modelBuilder.Entity("FritApi.Models.CsopaActivitat", b =>
                {
                    b.Property<int>("CsopaActivitatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CsopaActivitatId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipus")
                        .HasColumnType("integer");

                    b.Property<string>("Titol")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("integer");

                    b.HasKey("CsopaActivitatId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TenantId");

                    b.HasIndex("Tipus");

                    b.HasIndex("UsuarioCreadorId");

                    b.ToTable("CsopaActivitats");
                });

            modelBuilder.Entity("FritApi.Models.CsopaAssistencia", b =>
                {
                    b.Property<int>("CsopaAssistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CsopaAssistenciaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CsopaActivitatId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreMostrado")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("CsopaAssistenciaId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("CsopaActivitatId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("CsopaAssistencies");
                });

            modelBuilder.Entity("FritApi.Models.Encuesta", b =>
                {
                    b.Property<int>("EncuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EncuestaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<bool>("EsAnonima")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsVotacion")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PermiteEditarRespuesta")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublicadaAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("integer");

                    b.Property<int>("VisibilidadResultados")
                        .HasColumnType("integer");

                    b.HasKey("EncuestaId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("TenantId", "Estado", "FechaCierre");

                    b.ToTable("Encuestas");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaDestinatario", b =>
                {
                    b.Property<int>("EncuestaDestinatarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EncuestaDestinatarioId"));

                    b.Property<int>("EncuestaId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("EncuestaDestinatarioId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EncuestaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("EncuestaDestinatarios");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaOpcion", b =>
                {
                    b.Property<int>("EncuestaOpcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EncuestaOpcionId"));

                    b.Property<int>("EncuestaPreguntaId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("EncuestaOpcionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("EncuestaPreguntaId", "Orden");

                    b.ToTable("EncuestaOpciones");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaPregunta", b =>
                {
                    b.Property<int>("EncuestaPreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EncuestaPreguntaId"));

                    b.Property<string>("Ayuda")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<int?>("CondicionOpcionOrden")
                        .HasColumnType("integer");

                    b.Property<int?>("CondicionPreguntaOrden")
                        .HasColumnType("integer");

                    b.Property<int>("EncuestaId")
                        .HasColumnType("integer");

                    b.Property<int?>("Maximo")
                        .HasColumnType("integer");

                    b.Property<int?>("Minimo")
                        .HasColumnType("integer");

                    b.Property<bool>("Obligatoria")
                        .HasColumnType("boolean");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("EncuestaPreguntaId");

                    b.HasIndex("TenantId");

                    b.HasIndex("EncuestaId", "Orden");

                    b.ToTable("EncuestaPreguntas");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaRespuesta", b =>
                {
                    b.Property<int>("EncuestaRespuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EncuestaRespuestaId"));

                    b.Property<int>("EncuestaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("EncuestaRespuestaId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EncuestaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("EncuestaRespuestas");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaRespuestaOpcion", b =>
                {
                    b.Property<int>("EncuestaRespuestaOpcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EncuestaRespuestaOpcionId"));

                    b.Property<int>("EncuestaOpcionId")
                        .HasColumnType("integer");

                    b.Property<int>("EncuestaRespuestaValorId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("EncuestaRespuestaOpcionId");

                    b.HasIndex("EncuestaOpcionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("EncuestaRespuestaValorId", "EncuestaOpcionId")
                        .IsUnique();

                    b.ToTable("EncuestaRespuestaOpciones");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaRespuestaValor", b =>
                {
                    b.Property<int>("EncuestaRespuestaValorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EncuestaRespuestaValorId"));

                    b.Property<int>("EncuestaPreguntaId")
                        .HasColumnType("integer");

                    b.Property<int>("EncuestaRespuestaId")
                        .HasColumnType("integer");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("EncuestaRespuestaValorId");

                    b.HasIndex("EncuestaPreguntaId");

                    b.HasIndex("TenantId");

                    b.HasIndex("EncuestaRespuestaId", "EncuestaPreguntaId")
                        .IsUnique();

                    b.ToTable("EncuestaRespuestaValores");
                });

            modelBuilder.Entity("FritApi.Models.Juego", b =>
                {
                    b.Property<int>("JuegoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JuegoId"));

                    b.Property<int?>("BggId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DificultadBgg")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<bool>("EsPropiedadTenant")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("FechaAdquisicion")
                        .HasColumnType("date");

                    b.Property<int?>("JuegoBaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumeroJugadoresMax")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroJugadoresMin")
                        .HasColumnType("integer");

                    b.Property<int>("PropietarioId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Pvp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("JuegoId");

                    b.HasIndex("JuegoBaseId");

                    b.HasIndex("PropietarioId");

                    b.HasIndex("TenantId");

                    b.ToTable("Juegos");
                });

            modelBuilder.Entity("FritApi.Models.ManualMedalla", b =>
                {
                    b.Property<int>("ManualMedallaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ManualMedallaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("ManualMedallaId");

                    b.HasIndex("TenantId");

                    b.ToTable("ManualMedallas");
                });

            modelBuilder.Entity("FritApi.Models.ManualMedallaUsuario", b =>
                {
                    b.Property<int>("ManualMedallaUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ManualMedallaUsuarioId"));

                    b.Property<int>("ManualMedallaId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ManualMedallaUsuarioId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ManualMedallaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("ManualMedallaUsuarios");
                });

            modelBuilder.Entity("FritApi.Models.NotificationPreference", b =>
                {
                    b.Property<int>("NotificationPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationPreferenceId"));

                    b.Property<bool>("CambioPreferenciaJuego")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("Encuesta")
                        .HasColumnType("boolean");

                    b.Property<bool>("NuevaPartida")
                        .HasColumnType("boolean");

                    b.Property<bool>("NuevaRemada")
                        .HasColumnType("boolean");

                    b.Property<int>("PuntuacionMinima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<bool>("RecordatorioDomingo")
                        .HasColumnType("boolean");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<bool>("VotacionPelicula")
                        .HasColumnType("boolean");

                    b.HasKey("NotificationPreferenceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TenantId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("FritApi.Models.Partida", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartidaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("JuegoId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroJugadores")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("integer");

                    b.HasKey("PartidaId");

                    b.HasIndex("JuegoId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioCreadorId");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("FritApi.Models.PartidaJugador", b =>
                {
                    b.Property<int>("PartidaJugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartidaJugadorId"));

                    b.Property<string>("NombreMostrado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Puntos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("PartidaJugadorId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("PartidaId", "Posicion");

                    b.ToTable("PartidaJugadores");
                });

            modelBuilder.Entity("FritApi.Models.PendentCompra", b =>
                {
                    b.Property<int>("PendentCompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PendentCompraId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Link")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Quantitat")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("PendentCompraId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PendentsCompra");
                });

            modelBuilder.Entity("FritApi.Models.PushSubscription", b =>
                {
                    b.Property<int>("PushSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PushSubscriptionId"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("PushSubscriptionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TenantId", "Endpoint")
                        .IsUnique();

                    b.HasIndex("TenantId", "UsuarioId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("FritApi.Models.Remada", b =>
                {
                    b.Property<int>("RemadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RemadaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("NombreJocs")
                        .HasColumnType("integer");

                    b.Property<int>("PuntsPerJugador")
                        .HasColumnType("integer");

                    b.Property<int>("TempsDisponibleMinuts")
                        .HasColumnType("integer");

                    b.Property<int>("TempsMinimMinuts")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("integer");

                    b.HasKey("RemadaId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioCreadorId");

                    b.ToTable("Remades");
                });

            modelBuilder.Entity("FritApi.Models.RemadaJuego", b =>
                {
                    b.Property<int>("RemadaJuegoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RemadaJuegoId"));

                    b.Property<int>("JuegoId")
                        .HasColumnType("integer");

                    b.Property<string>("JuegoNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.Property<int>("RemadaId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("RemadaJuegoId");

                    b.HasIndex("JuegoId");

                    b.HasIndex("TenantId");

                    b.HasIndex("RemadaId", "JuegoId")
                        .IsUnique();

                    b.ToTable("RemadaJocs");
                });

            modelBuilder.Entity("FritApi.Models.RemadaJugador", b =>
                {
                    b.Property<int>("RemadaJugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RemadaJugadorId"));

                    b.Property<int>("Punts")
                        .HasColumnType("integer");

                    b.Property<int>("RemadaId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("RemadaJugadorId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("RemadaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("RemadaJugadors");
                });

            modelBuilder.Entity("FritApi.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantId"));

                    b.Property<bool>("Actiu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TenantId");

                    b.HasIndex("Codi")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("FritApi.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("EsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsUsuarioExterno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Grupo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FritApi.Models.UsuarioJuegoOrden", b =>
                {
                    b.Property<int>("UsuarioJuegoOrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioJuegoOrdenId"));

                    b.Property<int>("JuegoId")
                        .HasColumnType("integer");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioJuegoOrdenId");

                    b.HasIndex("JuegoId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId", "JuegoId")
                        .IsUnique();

                    b.ToTable("UsuarioJuegoOrdenes");
                });

            modelBuilder.Entity("FritApi.Models.AuditAuthorizedUser", b =>
                {
                    b.HasOne("FritApi.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("FritApi.Models.AuditAuthorizedUser", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FritApi.Models.CinePelicula", b =>
                {
                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("FritApi.Models.CineValoracion", b =>
                {
                    b.HasOne("FritApi.Models.CinePelicula", "CinePelicula")
                        .WithMany("Valoraciones")
                        .HasForeignKey("CinePeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CinePelicula");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.CsopaActivitat", b =>
                {
                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("FritApi.Models.CsopaAssistencia", b =>
                {
                    b.HasOne("FritApi.Models.CsopaActivitat", "CsopaActivitat")
                        .WithMany("Assistencies")
                        .HasForeignKey("CsopaActivitatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CsopaActivitat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.Encuesta", b =>
                {
                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaDestinatario", b =>
                {
                    b.HasOne("FritApi.Models.Encuesta", "Encuesta")
                        .WithMany("Destinatarios")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encuesta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaOpcion", b =>
                {
                    b.HasOne("FritApi.Models.EncuestaPregunta", "Pregunta")
                        .WithMany("Opciones")
                        .HasForeignKey("EncuestaPreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaPregunta", b =>
                {
                    b.HasOne("FritApi.Models.Encuesta", "Encuesta")
                        .WithMany("Preguntas")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Encuesta");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaRespuesta", b =>
                {
                    b.HasOne("FritApi.Models.Encuesta", "Encuesta")
                        .WithMany("Respuestas")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Encuesta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaRespuestaOpcion", b =>
                {
                    b.HasOne("FritApi.Models.EncuestaOpcion", "Opcion")
                        .WithMany()
                        .HasForeignKey("EncuestaOpcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.EncuestaRespuestaValor", "Valor")
                        .WithMany("Opciones")
                        .HasForeignKey("EncuestaRespuestaValorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Opcion");

                    b.Navigation("Valor");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaRespuestaValor", b =>
                {
                    b.HasOne("FritApi.Models.EncuestaPregunta", "Pregunta")
                        .WithMany()
                        .HasForeignKey("EncuestaPreguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.EncuestaRespuesta", "Respuesta")
                        .WithMany("Valores")
                        .HasForeignKey("EncuestaRespuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pregunta");

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("FritApi.Models.Juego", b =>
                {
                    b.HasOne("FritApi.Models.Juego", "JuegoBase")
                        .WithMany("Expansiones")
                        .HasForeignKey("JuegoBaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FritApi.Models.Usuario", "Propietario")
                        .WithMany()
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JuegoBase");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("FritApi.Models.ManualMedalla", b =>
                {
                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FritApi.Models.ManualMedallaUsuario", b =>
                {
                    b.HasOne("FritApi.Models.ManualMedalla", "ManualMedalla")
                        .WithMany("Usuarios")
                        .HasForeignKey("ManualMedallaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManualMedalla");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.NotificationPreference", b =>
                {
                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.Partida", b =>
                {
                    b.HasOne("FritApi.Models.Juego", "Juego")
                        .WithMany("Partidas")
                        .HasForeignKey("JuegoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Juego");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("FritApi.Models.PartidaJugador", b =>
                {
                    b.HasOne("FritApi.Models.Partida", "Partida")
                        .WithMany("Jugadores")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Partida");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.PendentCompra", b =>
                {
                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.PushSubscription", b =>
                {
                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.Remada", b =>
                {
                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("FritApi.Models.RemadaJuego", b =>
                {
                    b.HasOne("FritApi.Models.Juego", "Juego")
                        .WithMany()
                        .HasForeignKey("JuegoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Remada", "Remada")
                        .WithMany("Jocs")
                        .HasForeignKey("RemadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Juego");

                    b.Navigation("Remada");
                });

            modelBuilder.Entity("FritApi.Models.RemadaJugador", b =>
                {
                    b.HasOne("FritApi.Models.Remada", "Remada")
                        .WithMany("Jugadors")
                        .HasForeignKey("RemadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Remada");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.Usuario", b =>
                {
                    b.HasOne("FritApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FritApi.Models.UsuarioJuegoOrden", b =>
                {
                    b.HasOne("FritApi.Models.Juego", "Juego")
                        .WithMany()
                        .HasForeignKey("JuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Juego");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.CinePelicula", b =>
                {
                    b.Navigation("Valoraciones");
                });

            modelBuilder.Entity("FritApi.Models.CsopaActivitat", b =>
                {
                    b.Navigation("Assistencies");
                });

            modelBuilder.Entity("FritApi.Models.Encuesta", b =>
                {
                    b.Navigation("Destinatarios");

                    b.Navigation("Preguntas");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaPregunta", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaRespuesta", b =>
                {
                    b.Navigation("Valores");
                });

            modelBuilder.Entity("FritApi.Models.EncuestaRespuestaValor", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("FritApi.Models.Juego", b =>
                {
                    b.Navigation("Expansiones");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("FritApi.Models.ManualMedalla", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FritApi.Models.Partida", b =>
                {
                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("FritApi.Models.Remada", b =>
                {
                    b.Navigation("Jocs");

                    b.Navigation("Jugadors");
                });
#pragma warning restore 612, 618
        }
    }
}
