// <auto-generated />
using System;
using FritApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FritApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612093417_AddManualMedallas")]
    partial class AddManualMedallas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FritApi.Models.Juego", b =>
                {
                    b.Property<int>("JuegoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JuegoId"));

                    b.Property<int?>("BggId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DificultadBgg")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<DateOnly?>("FechaAdquisicion")
                        .HasColumnType("date");

                    b.Property<int?>("JuegoBaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumeroJugadoresMax")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroJugadoresMin")
                        .HasColumnType("integer");

                    b.Property<int>("PropietarioId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Pvp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("JuegoId");

                    b.HasIndex("JuegoBaseId");

                    b.HasIndex("PropietarioId");

                    b.ToTable("Juegos");
                });

            modelBuilder.Entity("FritApi.Models.ManualMedalla", b =>
                {
                    b.Property<int>("ManualMedallaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ManualMedallaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ManualMedallaId");

                    b.ToTable("ManualMedallas");
                });

            modelBuilder.Entity("FritApi.Models.ManualMedallaUsuario", b =>
                {
                    b.Property<int>("ManualMedallaUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ManualMedallaUsuarioId"));

                    b.Property<int>("ManualMedallaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ManualMedallaUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ManualMedallaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("ManualMedallaUsuarios");
                });

            modelBuilder.Entity("FritApi.Models.Partida", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartidaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("JuegoId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroJugadores")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("integer");

                    b.HasKey("PartidaId");

                    b.HasIndex("JuegoId");

                    b.HasIndex("UsuarioCreadorId");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("FritApi.Models.PartidaJugador", b =>
                {
                    b.Property<int>("PartidaJugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartidaJugadorId"));

                    b.Property<string>("NombreMostrado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Puntos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("PartidaJugadorId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("PartidaId", "Posicion");

                    b.ToTable("PartidaJugadores");
                });

            modelBuilder.Entity("FritApi.Models.PendentCompra", b =>
                {
                    b.Property<int>("PendentCompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PendentCompraId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Link")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Quantitat")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("PendentCompraId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PendentsCompra");
                });

            modelBuilder.Entity("FritApi.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Grupo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FritApi.Models.UsuarioJuegoOrden", b =>
                {
                    b.Property<int>("UsuarioJuegoOrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioJuegoOrdenId"));

                    b.Property<int>("JuegoId")
                        .HasColumnType("integer");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioJuegoOrdenId");

                    b.HasIndex("JuegoId");

                    b.HasIndex("UsuarioId", "JuegoId")
                        .IsUnique();

                    b.ToTable("UsuarioJuegoOrdenes");
                });

            modelBuilder.Entity("FritApi.Models.Juego", b =>
                {
                    b.HasOne("FritApi.Models.Juego", "JuegoBase")
                        .WithMany("Expansiones")
                        .HasForeignKey("JuegoBaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FritApi.Models.Usuario", "Propietario")
                        .WithMany()
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JuegoBase");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("FritApi.Models.ManualMedallaUsuario", b =>
                {
                    b.HasOne("FritApi.Models.ManualMedalla", "ManualMedalla")
                        .WithMany("Usuarios")
                        .HasForeignKey("ManualMedallaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManualMedalla");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.Partida", b =>
                {
                    b.HasOne("FritApi.Models.Juego", "Juego")
                        .WithMany("Partidas")
                        .HasForeignKey("JuegoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Juego");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("FritApi.Models.PartidaJugador", b =>
                {
                    b.HasOne("FritApi.Models.Partida", "Partida")
                        .WithMany("Jugadores")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Partida");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.PendentCompra", b =>
                {
                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.UsuarioJuegoOrden", b =>
                {
                    b.HasOne("FritApi.Models.Juego", "Juego")
                        .WithMany()
                        .HasForeignKey("JuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FritApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Juego");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FritApi.Models.Juego", b =>
                {
                    b.Navigation("Expansiones");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("FritApi.Models.ManualMedalla", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FritApi.Models.Partida", b =>
                {
                    b.Navigation("Jugadores");
                });
#pragma warning restore 612, 618
        }
    }
}
